[project]
name = "tg-yt-dlp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiohttp>=3.11.13",
    "aioprometheus>=23.12.0",
    "python-telegram-bot>=21.10",
    "yt-dlp>=2025.2.19",
]
