name: "Dependabot Automerge - Action"

on:
  pull_request:

jobs:
  worker:
    permissions: write-all
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    steps:
      - name: automerge
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.AUTOMERGE_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;

            await github.rest.pulls.createReview({
              owner,
              repo,
              pull_number,
              event: 'APPROVE'
            });

            await github.rest.pulls.merge({
              owner,
              repo,
              pull_number
            });

