name: On push to master

on:
  push:
    branches: [master]

jobs:
  image:
    name: Create and publish a Docker image
    uses: ./.github/workflows/do_build_image.yml
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
